cross/binutils-*: hotfix for file conflict with non-cross binutils
Newly generated binutils package has file conflicsts with
non-cross binutils.

  ERROR: binutils-2.37-r3: trying to overwrite usr/lib/bfd-plugins/libdep.so
         owned by binutils-aarch64-2.37-r3.

Attmpt to fix this quickly to unblock bpo and users