pmaports.cfg: set pmbootstrap_min_version=1.47.0
With recent cross/gcc-* upgrades, we actually require pmbootstrap
1.47.0 to avoid the following error:
  ERROR: Invalid pkgver '${_pkgbase}_git${_pkgsnap}' in APKBUILD: /home/user/.local/var/pmbootstrap/cache_git/pmaports/cross/gcc-aarch64/APKBUILD