temp/sonnet: fork from Alpine for armv7
Alpine's build bot is stuck on another package, but this needs to be
rebuilt against the recently updated libhunspell. Otherwise Plasma
Mobile cannot be installed, as pmbootstrap fails with:

ERROR: Could not find dependency 'so:libhunspell-1.6.so.0' in any aports folder or APKINDEX.

I've tested that this builds properly.