main/postmarketos-mkinitfs: provide initramfs-generator (MR 3219)
Alpine provides a 'initramfs-generator' thing now that the alpine
linux-* depend on explicitly. This sets postmarketos-mkinitfs to be the
preferred provider of that virtual package.

Fixes:
        ERROR: unable to select packages:
          postmarketos-mkinitfs-1.4.1-r5:
            conflicts: mkinitfs-3.6.1-r2[mkinitfs=3.6.0]
            satisfies: postmarketos-base-20-r1[postmarketos-mkinitfs]
                       postmarketos-base-nofde-20-r1[postmarketos-mkinitfs]
                       .pmbootstrap-20220610.215815[postmarketos-mkinitfs]
                       .pmbootstrap-20220610.215815[mkinitfs]
          mkinitfs-3.6.1-r2:
            conflicts: postmarketos-mkinitfs-1.4.1-r5
            satisfies: .pmbootstrap-20220610.215815[mkinitfs]
                       linux-rpi-5.15.45-r1[initramfs-generator]
          .pmbootstrap-20220610.215815:
            masked in: cache
            satisfies: world[.pmbootstrap=20220610.215815]

Also see:
        30d7b88324 (aports) main/mkinitfs: provide initramfs-generator
        4fac61c826 (aports) main/linux-lts: replace mkinitfs with initramfs-generator