modem/msm-modem: add rmtfs-openrc dependency (MR 1274)
It is possible for msm-modem to get installed before
rmtfs-openrc, which causes the following error in
post-install:

 * rc-update: service `rmtfs' does not exist
ERROR: msm-modem-1-r0.post-install: script exited with error 1

Add a dependency to ensure rmtfs-openrc gets installed first