main/urfkill: depend on polkit-elogind, not polkit
Fix the following error when installing postmarketos-ui-plasma-mobile:

ERROR: unsatisfiable constraints:
  polkit-elogind-0.116-r1:
    breaks: polkit-dev-0.116-r0[polkit=0.116-r0]
    satisfies: polkit-kde-agent-1-5.17.3-r0[polkit-elogind]
               .pmbootstrap-20191121.210534[polkit-elogind]
               consolekit2-1.2.1-r1[polkit]
               consolekit2-1.2.1-r1[so:libpolkit-gobject-1.so.0]
               networkmanager-1.20.6-r0[so:libpolkit-agent-1.so.0]
               networkmanager-1.20.6-r0[so:libpolkit-gobject-1.so.0]
               polkit-qt-1-0.113.0-r0[so:libpolkit-agent-1.so.0]
               polkit-qt-1-0.113.0-r0[so:libpolkit-gobject-1.so.0]
               accountsservice-0.6.55-r0[so:libpolkit-gobject-1.so.0]
               urfkill-0.5.0_git20170118-r0[so:libpolkit-gobject-1.so.0]

This is the reason, why the pmbootstrap qemu test (which performs a full
plasma mobile installation and checks running processes) check failed:
https://postmarketos.gitlab.io/-/pmbootstrap/-/jobs/357942365/artifacts/log_testsuite.txt