temp/mesa-git: build for arm, not for all arches
Avoid build failure for x86:

>>> mesa-git-glapi*: Running postcheck for mesa-git-glapi
>>> ERROR: mesa-git-glapi*: Found textrels:
TEXTREL  /home/pmos/build/pkg/mesa-git-glapi/usr/lib/libglapi.so.0.0.0

The package is only used for armhf, armv7, aarch64 devices currently, so
change the arch line in the APKBUILD accordingly.

$ cd device
$ for i in $(git grep mesa-git | cut -d/ -f1); do grep -H arch $i/deviceinfo; done
device-asus-flo/deviceinfo:deviceinfo_arch="armhf"
device-lg-hammerhead/deviceinfo:deviceinfo_arch="armv7"
device-pine-a64lts/deviceinfo:deviceinfo_arch="aarch64"
device-pine-dontbeevil/deviceinfo:deviceinfo_arch="aarch64"
device-sony-castor-windy/deviceinfo:deviceinfo_arch="armhf"
device-sony-sirius/deviceinfo:deviceinfo_arch="armv7"

[ci:skip-vercheck]: only changed arch line
Fixes: ce7e4d79e1b4d25e6912699abe1955a99cbf33f7 ("temp/mesa-git: new aport (!524)")