fairphone-fp2: bump pkgrel (!1079)
The pkgrel bump in !1032 got lost during a rebase, rebuild the package to fix:
ERROR: Could not find dependency 'modem-qcom-msm-mainline-common' in any aports folder or APKINDEX.