temp/epiphany: upgrade to 41.3 (MR 2792)
Fix current version of epiphany not being installable because of soname
bump in libportal:
  / # apk add epiphany
  ERROR: unable to select packages:
    so:libportal.so.0 (no such package):
      required by: epiphany-9999_git20210916-r0[so:libportal.so.0]

Upgrade to 41.3 while at it, and drop the firefox sync dialog patch
since it doesn't apply cleanly anymore. Only the disable fullscreen
patch is really important, Pablo only included the firefox sync patch
because it applied cleanly.