cross/gcc-{armv7,aarch64}: upgrade to 11.2.1_git20220219-r4
Fix the following error:

ERROR: unable to select packages:
  libstdc++-11.2.1_git20220219-r4:
    breaks: g++-aarch64-11.2.1_git20220219-r3[libstdc++=11.2.1_git20220219-r3]
    satisfies: gcc-11.2.1_git20220219-r4[so:libstdc++.so.6]
               binutils-2.38-r3[so:libstdc++.so.6]
               ccache-4.6.1-r0[so:libstdc++.so.6]
  gcc-11.2.1_git20220219-r4:
    breaks: g++-aarch64-11.2.1_git20220219-r3[gcc=11.2.1_git20220219-r3]

The new version does not seem to be in the armhf repos yet so skip that
one for now.