temp/evince: drop aport (MR 3484)
Upstream has evince 43 now, which seems to be adapted (tested on the
Librem 5), and the old evince in this package depends on a package that
no longer exists:
        ERROR: unable to select packages:
          so:libgnome-desktop-3.so.19 (no such package):
            required by: evince-9999_git20211009-r2[so:libgnome-desktop-3.so.19]